name: Integration Tests

on:
  pull_request:
    branches: [ testing, acceptance, main ]
    types: [opened, synchronize, reopened]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Integration Tests
      run: |
        # Run tests with the integration tag
        mvn -B test -Dgroups="integration"
        
    - name: Upload Integration Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: target/surefire-reports/
