name: Java Build

on:
  push:
    branches: [ development]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ development, testing, acceptance, main ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]  # Test only on Java 17
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Tests
      run: mvn test
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-artifacts-java-${{ matrix.java-version }}
        path: |
          target/*.jar
          !target/*-sources.jar
          !target/*-javadoc.jar
          
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: target/surefire-reports/
